### ISSUE TITLE
Improve 'Attempted to set the feature state of a feature with no ID' warning 

### ISSUE THREAD

**Issue by nsiebenaller** [dimapio/map-gl#10]
When a `Layer` attempts to set a feature state with no ID, a warning is displayed. However, this warning is generic and does not include context about:

1. What layer triggered this warning
2. What source this layer corresponds to
3. What the structure of the feature looks like.

We should improve this warning message to include this context.

**Comment by nsiebenaller** [comment]
@garretteklof I've assigned this to you based on our convo

**Comment by garretteklof** [comment]
@nsiebenaller I will not let you down 🫡
